# Generated by Django 5.0.6 on 2026-03-12 00:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Inicio del Periodo')),
                ('period_end', models.DateField(verbose_name='Fin del Periodo')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Base')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonificaciones')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Deducciones')),
                ('advances_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Adelantos Descontados')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total a Pagar')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia')], default='CASH', max_length=20, verbose_name='Metodo de Pago')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobado'), ('PAID', 'Pagado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Liquidacion de Salario',
                'verbose_name_plural': 'Liquidaciones de Salario',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=200, verbose_name='Concepto')),
                ('item_type', models.CharField(choices=[('EARNING', 'Haberes'), ('DEDUCTION', 'Descuento')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='staff.salarysettlement', verbose_name='Liquidacion')),
            ],
            options={
                'verbose_name': 'Item de Liquidacion',
                'verbose_name_plural': 'Items de Liquidacion',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MANAGER', 'Gerente'), ('WAITER', 'Mozo'), ('BARTENDER', 'Bartender'), ('CHEF', 'Cocinero'), ('CASHIER', 'Cajero'), ('CLEANER', 'Limpieza')], max_length=20, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('address', models.TextField(blank=True, verbose_name='Direccion')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salario Base')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tarifa por Hora')),
                ('payment_type', models.CharField(choices=[('MONTHLY', 'Mensual'), ('HOURLY', 'Por Hora')], default='MONTHLY', max_length=20, verbose_name='Tipo de Pago')),
                ('dni', models.CharField(blank=True, max_length=20, verbose_name='DNI')),
                ('emergency_contact', models.CharField(blank=True, max_length=200, verbose_name='Contacto de Emergencia')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro del Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='salarysettlement',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='staff.staffmember', verbose_name='Personal'),
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='Motivo')),
                ('settled', models.BooleanField(default=False, verbose_name='Liquidado')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='staff.staffmember', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Adelanto de Salario',
                'verbose_name_plural': 'Adelantos de Salario',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de Entrada')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Salida')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas Trabajadas')),
                ('shift_type', models.CharField(choices=[('MORNING', 'Manana'), ('AFTERNOON', 'Tarde'), ('NIGHT', 'Noche'), ('FULL', 'Jornada Completa')], default='MORNING', max_length=20, verbose_name='Tipo de Turno')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notas')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.staffmember', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Turno de Trabajo',
                'verbose_name_plural': 'Turnos de Trabajo',
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
