# Generated by Django 5.0.6 on 2026-03-12 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Numero')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Capacidad')),
                ('status', models.CharField(choices=[('FREE', 'Libre'), ('OCCUPIED', 'Ocupada'), ('RESERVED', 'Reservada'), ('CLEANING', 'Limpieza')], default='FREE', max_length=20, verbose_name='Estado')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='tables/qr/', verbose_name='Codigo QR')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TableArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('party_size', models.PositiveIntegerField(default=2, verbose_name='Numero de Personas')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('SEATED', 'Sentado'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'No se presento')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tables.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.AddField(
            model_name='table',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='tables.tablearea', verbose_name='Area'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('number', 'area')},
        ),
    ]
