# Generated by Django 5.0.6 on 2026-03-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='BackyardFlow POS', max_length=100, verbose_name='Nombre del local')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('currency_symbol', models.CharField(default='$', max_length=5, verbose_name='Símbolo de moneda')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IVA %')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/', verbose_name='Logo')),
                ('receipt_footer', models.TextField(blank=True, verbose_name='Pie de ticket')),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
            },
        ),
    ]
