# Generated by Django 5.0.6 on 2026-03-12 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='menu/categories/', verbose_name='Icono')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoria del Menu',
                'verbose_name_plural': 'Categorias del Menu',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('item_type', models.CharField(choices=[('FOOD', 'Comida'), ('DRINK', 'Bebida'), ('DESSERT', 'Postre'), ('OTHER', 'Otro')], default='FOOD', max_length=20, verbose_name='Tipo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/items/', verbose_name='Imagen')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('preparation_time', models.PositiveIntegerField(default=15, verbose_name='Tiempo de Preparacion (min)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='menu.menucategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Item del Menu',
                'verbose_name_plural': 'Items del Menu',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones')),
                ('servings', models.PositiveIntegerField(default=1, verbose_name='Porciones')),
                ('preparation_time', models.PositiveIntegerField(default=15, verbose_name='Tiempo de Preparacion (min)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='menu.menuitem', verbose_name='Item del Menu')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('units', 'Unidades'), ('portions', 'Porciones')], max_length=20, verbose_name='Unidad')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_usages', to='inventory.ingredient', verbose_name='Ingrediente')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.recipe', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Ingrediente de Receta',
                'verbose_name_plural': 'Ingredientes de Receta',
            },
        ),
    ]
