# Generated by Django 5.0.6 on 2026-03-12 00:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_register', '0001_initial'),
        ('menu', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numero de Comanda')),
                ('order_type', models.CharField(choices=[('DINE_IN', 'En Mesa'), ('TAKEOUT', 'Para Llevar'), ('DELIVERY', 'Delivery')], default='DINE_IN', max_length=20, verbose_name='Tipo')),
                ('waiter_type', models.CharField(choices=[('HUMAN', 'Mozo'), ('VIRTUAL', 'Virtual (QR)')], default='HUMAN', max_length=20, verbose_name='Tipo de Mozo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Preparacion'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cash_register.cashsession', verbose_name='Sesion de Caja')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tables.table', verbose_name='Mesa')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Mozo')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Notas')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PREPARING', 'Preparando'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('sent_to_kitchen_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem', verbose_name='Item del Menu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Comanda')),
            ],
            options={
                'verbose_name': 'Item de Comanda',
                'verbose_name_plural': 'Items de Comanda',
            },
        ),
        migrations.CreateModel(
            name='VirtualWaiterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_sessions', to='orders.order', verbose_name='Comanda')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_sessions', to='tables.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Sesion de Mozo Virtual',
                'verbose_name_plural': 'Sesiones de Mozo Virtual',
            },
        ),
    ]
